document.addEventListener("DOMContentLoaded",()=>{
  const header=document.querySelector(".site-header"),menuToggle=document.querySelector(".menu-toggle"),navigation=document.querySelector(".main-navigation");
  const visualFixes=document.createElement("style");
  visualFixes.textContent=`.section-dark,.craft,.contact{margin-top:28px!important;margin-bottom:28px!important}.site-header{border-bottom:none!important;box-shadow:none}.collection-leather,.collection-wood{min-height:590px!important;overflow:hidden!important}.collection-leather .collection-overlay,.collection-wood .collection-overlay{z-index:1!important}.collection-leather .collection-content,.collection-wood .collection-content{z-index:5!important}.site-gallery{display:none;padding:80px 0;background:var(--espresso);color:var(--cream)}.site-gallery.is-open{display:block}.site-gallery-heading{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:30px}.site-gallery-heading h2{font-size:clamp(42px,5vw,68px)}.site-gallery-heading p{margin:0;color:#b9aea5;font-size:13px}.site-gallery-main{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(220px,.7fr);gap:24px}.site-gallery-main-photo{min-height:520px;background:#17100c;border:1px solid rgba(255,255,255,.16);display:flex;align-items:center;justify-content:center;overflow:hidden}.site-gallery-main-photo img{width:100%;height:100%;object-fit:contain}.site-gallery-thumbs{display:grid;grid-template-columns:1fr;gap:16px}.site-gallery-thumb{border:1px solid rgba(255,255,255,.16);background:#17100c;padding:0;cursor:pointer;overflow:hidden;aspect-ratio:1}.site-gallery-thumb img{width:100%;height:100%;object-fit:cover}.site-gallery-close{border:1px solid rgba(255,255,255,.3);background:transparent;color:var(--cream);padding:10px 16px;font-size:10px;font-weight:600;letter-spacing:.15em;text-transform:uppercase;cursor:pointer}.site-gallery-close:hover{background:rgba(255,255,255,.08)}@media(max-width:700px){.site-gallery{padding:60px 0}.site-gallery-heading{align-items:flex-start;flex-direction:column}.site-gallery-main{grid-template-columns:1fr}.site-gallery-main-photo{min-height:360px}.site-gallery-thumbs{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(visualFixes);
  if(menuToggle&&navigation){menuToggle.addEventListener("click",()=>{const open=navigation.classList.toggle("open");menuToggle.classList.toggle("active",open);menuToggle.setAttribute("aria-expanded",String(open));menuToggle.setAttribute("aria-label",open?"Close navigation":"Open navigation")});navigation.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{navigation.classList.remove("open");menuToggle.classList.remove("active");menuToggle.setAttribute("aria-expanded","false");menuToggle.setAttribute("aria-label","Open navigation")}))}
  const updateHeader=()=>{if(header)header.style.boxShadow=window.scrollY>20?"0 12px 35px rgba(23,19,15,.08)":"none"};window.addEventListener("scroll",updateHeader,{passive:true});updateHeader();
  const orderStyles=document.createElement("link");orderStyles.rel="stylesheet";orderStyles.href="order-form.css";document.head.appendChild(orderStyles);
  const orderNav=document.createElement("a");orderNav.href="#custom-order";orderNav.textContent="Custom Quote";if(navigation)navigation.appendChild(orderNav);
  const contact=document.querySelector("#contact");
  if(contact&&!document.querySelector("#custom-order")){
    const order=document.createElement("section");order.id="custom-order";
    order.innerHTML=`<div class="wrap order-grid"><div class="order-intro"><p class="eyebrow">THE BURNISH COMPANY • CUSTOM WORK</p><h2>Made for <em>one.</em></h2><p class="order-intro-copy">Every custom piece begins with a purpose. Tell us what you have in mind and we'll review the details and respond with a custom quote.</p><span class="order-tag">Individual. Purposeful. Handmade.</span></div><div class="order-card"><div class="order-card-header"><div><p class="eyebrow">CUSTOM QUOTE FORM</p><h3>Project Details</h3></div><span class="order-number">NO. 01</span></div><form class="order-form" id="custom-order-form"><div class="order-field"><label for="order-item">Item Name <span class="required">*</span></label><select id="order-item" name="item" required><option value="" selected disabled>Select an item</option><option value="Cutting Board">Cutting Board</option><option value="Wallet">Wallet</option></select></div><div class="order-field"><label for="order-option">Size / Style <span class="required">*</span></label><select id="order-option" name="option" required disabled><option value="" selected disabled>Select an option</option></select></div><div class="order-field"><label for="order-date">Date</label><input id="order-date" name="date" type="date"></div><div class="order-field"><label for="order-customer">Customer Name <span class="required">*</span></label><input id="order-customer" name="customer" type="text" placeholder="Your name" required></div><div class="order-field"><label for="order-email">Customer Email <span class="required">*</span></label><input id="order-email" name="email" type="email" placeholder="you@example.com" autocomplete="email" required></div><div class="order-field"><label for="order-material">Material</label><select id="order-material" name="material" required disabled><option value="" selected disabled>Select material</option></select></div><div class="order-field"><label for="order-feature">Juice Groove / Edge Dye</label><select id="order-feature" name="feature" required disabled><option value="" selected disabled>Select an option</option></select></div><div class="order-field full"><label for="order-special">Special Instructions</label><textarea id="order-special" name="special" placeholder="Any special requests or details for your piece."></textarea></div><div class="order-submit-row"><button class="button button-primary order-submit" type="submit">Send Quote Request</button><p class="order-note">Click once and your request will be sent directly to The Burnish Company. No email app is required.</p></div><div class="order-success" id="order-success">Thank you. Your quote request has been sent. We'll review the details and respond with your custom quote.</div></form></div></div>`;
    contact.parentNode.insertBefore(order,contact);
    const itemSelect=document.querySelector("#order-item"),optionSelect=document.querySelector("#order-option"),materialSelect=document.querySelector("#order-material"),featureSelect=document.querySelector("#order-feature");
    const woodOptions=["Walnut","Maple","Cherry"],dublinOptions=["Black","Brown Nut","English Tan"];
    const boardSizes=["Small (6\" × 12\")","Medium (9\" × 15\")","Large (12\" × 18\")"],walletStyles=["The Straumann","The Stine","The James"];
    const juiceOptions=["Yes","No"],edgeDyeOptions=["None","Brown","Black"];
    const setSelectOptions=(select,label,options,disabled=false)=>{select.innerHTML='<option value="" selected disabled>Select '+label+'</option>';options.forEach(option=>{const el=document.createElement("option");el.value=option;el.textContent=option;select.appendChild(el)});select.disabled=disabled};
    const updateOptions=()=>{const item=itemSelect.value;setSelectOptions(optionSelect,item==="Cutting Board"?"size":"wallet style",item==="Cutting Board"?boardSizes:item==="Wallet"?walletStyles:[],!item);setSelectOptions(materialSelect,item==="Cutting Board"?"wood type":item==="Wallet"?"Horween Dublin color":"material",item==="Cutting Board"?woodOptions:item==="Wallet"?dublinOptions:[],!item);setSelectOptions(featureSelect,item==="Cutting Board"?"juice groove":"edge dye",item==="Cutting Board"?juiceOptions:item==="Wallet"?edgeDyeOptions:[],!item);featureSelect.setAttribute("aria-label",item==="Cutting Board"?"Juice groove":item==="Wallet"?"Edge dye":"Additional option")};
    itemSelect.addEventListener("change",updateOptions);updateOptions();
    document.querySelector("#custom-order-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget;const submitButton=form.querySelector(".order-submit");const success=document.querySelector("#order-success");submitButton.disabled=true;submitButton.textContent="Sending…";success.classList.remove("is-visible");const data=new FormData(form);data.append("_subject",`Custom Quote Request — ${data.get("item")||"Burnish Company"}`);data.append("_replyto",data.get("email")||"");data.append("_template","table");data.append("_captcha","true");data.append("_url",window.location.href);try{const response=await fetch("https://formsubmit.co/ajax/theburnishcompany@gmail.com",{method:"POST",headers:{Accept:"application/json"},body:data});if(!response.ok)throw new Error("Submission failed");const result=await response.json();if(result.success===false)throw new Error("Submission failed");form.reset();updateOptions();success.textContent="Thank you. Your quote request has been sent. We'll review the details and respond with your custom quote.";success.classList.add("is-visible")}catch(error){success.textContent="We couldn't send your request right now. Please try again in a moment.";success.classList.add("is-visible")}finally{submitButton.disabled=false;submitButton.textContent="Send Quote Request"}});
  }

  // Product galleries: hidden until the collection icon is clicked.
  const collections=document.querySelector("#collections");
  if(collections&&!document.querySelector("#wallet-gallery")){
    const galleries=document.createElement("div");
    galleries.innerHTML=`<section id="wallet-gallery" class="site-gallery"><div class="wrap"><div class="site-gallery-heading"><div><p class="eyebrow">LEATHER GOODS</p><h2>The Ave</h2><p>A handcrafted wallet shown from multiple views.</p></div><button class="site-gallery-close" type="button">Close Gallery</button></div><div class="site-gallery-main"><div class="site-gallery-main-photo"><img src="photos/wallets/the-ave/IMG_3722.jpeg" alt="The Ave wallet main view"></div><div class="site-gallery-thumbs"><button class="site-gallery-thumb" type="button"><img src="photos/wallets/the-ave/IMG_3722.jpeg" alt="The Ave wallet front view"></button><button class="site-gallery-thumb" type="button"><img src="photos/wallets/the-ave/IMG_3723.jpeg" alt="The Ave wallet detail view"></button></div></div></div></section><section id="woodworking-gallery" class="site-gallery"><div class="wrap"><div class="site-gallery-heading"><div><p class="eyebrow">FINE WOODWORK</p><h2>Fine Woodworking</h2><p>A selection of handcrafted woodworking pieces.</p></div><button class="site-gallery-close" type="button">Close Gallery</button></div><div class="site-gallery-main"><div class="site-gallery-main-photo"><img src="photos/woodworking/44B4E7CF-BC14-4AA3-BE37-607FF00D6211.jpeg" alt="Fine woodworking main view"></div><div class="site-gallery-thumbs"><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/44B4E7CF-BC14-4AA3-BE37-607FF00D6211.jpeg" alt="Fine woodworking view 1"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/5995285E-4D0A-43AC-88C3-E676BD0FD377.jpeg" alt="Fine woodworking view 2"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/606FA773-1DAA-4E93-A696-E3887DC2BE37.jpeg" alt="Fine woodworking view 3"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/IMG_8987.jpeg" alt="Fine woodworking view 4"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/IMG_9053.jpeg" alt="Fine woodworking view 5"></button></div></div></div></section>`;
    const cards=collections.querySelector(".collection-grid");
    cards.insertAdjacentElement("afterend",galleries.firstElementChild);
    cards.parentNode.insertBefore(galleries.firstElementChild,collections.querySelector(".collection-grid").nextSibling);
    const woodGallery=document.createElement("section");
    woodGallery.id="woodworking-gallery";woodGallery.className="site-gallery";
    woodGallery.innerHTML=`<div class="wrap"><div class="site-gallery-heading"><div><p class="eyebrow">FINE WOODWORK</p><h2>Fine Woodworking</h2><p>A selection of handcrafted woodworking pieces.</p></div><button class="site-gallery-close" type="button">Close Gallery</button></div><div class="site-gallery-main"><div class="site-gallery-main-photo"><img src="photos/woodworking/44B4E7CF-BC14-4AA3-BE37-607FF00D6211.jpeg" alt="Fine woodworking main view"></div><div class="site-gallery-thumbs"><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/44B4E7CF-BC14-4AA3-BE37-607FF00D6211.jpeg" alt="Fine woodworking view 1"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/5995285E-4D0A-43AC-88C3-E676BD0FD377.jpeg" alt="Fine woodworking view 2"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/606FA773-1DAA-4E93-A696-E3887DC2BE37.jpeg" alt="Fine woodworking view 3"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/IMG_8987.jpeg" alt="Fine woodworking view 4"></button><button class="site-gallery-thumb" type="button"><img src="photos/woodworking/IMG_9053.jpeg" alt="Fine woodworking view 5"></button></div></div></div>`;
    galleries.appendChild(woodGallery);
    collections.appendChild(galleries);

    const openGallery=(id)=>{const gallery=document.getElementById(id);if(!gallery)return;gallery.classList.add("is-open");gallery.scrollIntoView({behavior:"smooth",block:"start"});const main=gallery.querySelector(".site-gallery-main-photo img");gallery.querySelectorAll(".site-gallery-thumb").forEach(button=>button.addEventListener("click",()=>{const image=button.querySelector("img");main.src=image.src;main.alt=image.alt},{once:true}))};
    document.querySelector(".collection-leather .collection-icon-link")?.addEventListener("click",event=>{event.preventDefault();openGallery("wallet-gallery")});
    document.querySelector(".collection-wood .collection-icon-link")?.addEventListener("click",event=>{event.preventDefault();openGallery("woodworking-gallery")});
    document.querySelectorAll(".site-gallery-close").forEach(button=>button.addEventListener("click",()=>button.closest(".site-gallery").classList.remove("is-open")));
  }

  const revealItems=document.querySelectorAll(".intro-grid,.collection-card,.value,.craft-grid,.contact-grid,#custom-order .order-card");if("IntersectionObserver"in window){const observer=new IntersectionObserver((entries,o)=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add("is-visible");o.unobserve(entry.target)}),{threshold:.12,rootMargin:"0px 0px -50px 0px"});revealItems.forEach(item=>{item.classList.add("reveal");observer.observe(item)})}
});
